import { cp, mkdir } from 'node:fs/promises';

await mkdir('dist/domain', { recursive: true });
await mkdir('dist/application', { recursive: true });
await mkdir('dist/stores', { recursive: true });
await cp('src/domain/models.js', 'dist/domain/models.js');
await cp('src/domain/simulation.js', 'dist/domain/simulation.js');
await cp('src/domain/permissions.js', 'dist/domain/permissions.js');
await cp('src/domain/audit.js', 'dist/domain/audit.js');
await cp('src/domain/offseason.js', 'dist/domain/offseason.js');
await cp('src/application/league-workflow.js', 'dist/application/league-workflow.js');
await cp('src/application/admin-summary.js', 'dist/application/admin-summary.js');
await cp('src/application/admin-service.js', 'dist/application/admin-service.js');
await cp('src/application/admin-commands.js', 'dist/application/admin-commands.js');
await cp('src/application/match-week-resolver.js', 'dist/application/match-week-resolver.js');
await cp('src/stores/local.js', 'dist/stores/local.js');
await cp('src/stores/game-store.js', 'dist/stores/game-store.js');
await cp('src/stores/sharepoint.js', 'dist/stores/sharepoint.js');
await cp('src/stores/spfx-client.js', 'dist/stores/spfx-client.js');
await cp('src/stores/sharepoint-provisioning.js', 'dist/stores/sharepoint-provisioning.js');
console.log('Copied domain, application, and store modules to dist/.');
