import { cp, mkdir, readFile, writeFile } from 'node:fs/promises';

const browserModules = [
  'src/domain/models.js',
  'src/domain/form.js',
  'src/domain/simulation.js',
  'src/domain/offseason.js',
  'src/domain/training.js',
  'src/stores/local.js'
];

function browserSource(source) {
  return source
    .replace(/^import .*;\r?\n/gm, '')
    .replace(/^export \{[^}]+\};?\r?\n?/gm, '')
    .replace(/\bexport (const|function|class)\b/g, '$1');
}

await mkdir('dist/domain', { recursive: true });
await mkdir('dist/application', { recursive: true });
await mkdir('dist/stores', { recursive: true });
await cp('src/domain/models.js', 'dist/domain/models.js');
await cp('src/domain/form.js', 'dist/domain/form.js');
await cp('src/domain/simulation.js', 'dist/domain/simulation.js');
await cp('src/domain/permissions.js', 'dist/domain/permissions.js');
await cp('src/domain/audit.js', 'dist/domain/audit.js');
await cp('src/domain/offseason.js', 'dist/domain/offseason.js');
await cp('src/domain/training.js', 'dist/domain/training.js');
await cp('src/application/league-workflow.js', 'dist/application/league-workflow.js');
await cp('src/application/admin-summary.js', 'dist/application/admin-summary.js');
await cp('src/application/admin-service.js', 'dist/application/admin-service.js');
await cp('src/application/admin-commands.js', 'dist/application/admin-commands.js');
await cp('src/application/match-week-resolver.js', 'dist/application/match-week-resolver.js');
await cp('src/stores/local.js', 'dist/stores/local.js');
await cp('src/stores/game-store.js', 'dist/stores/game-store.js');
await cp('src/stores/sharepoint.js', 'dist/stores/sharepoint.js');
await cp('src/stores/spfx-client.js', 'dist/stores/spfx-client.js');
await cp('src/stores/sharepoint-provisioning.js', 'dist/stores/sharepoint-provisioning.js');

const bundleParts = [];
for (const path of browserModules) {
  bundleParts.push(`/* ${path} */\n${browserSource(await readFile(path, 'utf8'))}`);
}
bundleParts.push(`/* src/browser/app.js */\n${browserSource(await readFile('src/browser/app.js', 'utf8'))}`);
await writeFile('dist/app.js', `/* Generated by scripts/build.mjs. Edit src/browser/app.js or src modules. */\n\n${bundleParts.join('\n\n')}`, 'utf8');

console.log('Copied modules and built the self-contained browser script in dist/.');
